[package]
name = "minspan"
version = "0.1.1"
edition = "2018"
description = "a package for determining the minimum span of one vector within another"
license = "MIT"
repository = "https://github.com/mwotton/minspan"

[dependencies]
